### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-younglust#1]
Super buen trabajo @younglust 

Algunas pistas para acabarlo:

- [x] Termina de añadir el componente PokemonList
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Elimina el código comentado
- [x] Apaña estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by younglust** [comment]
Hola @nasivuela 
Diría que ya están las modificaciones. El indentado lo cambié a 2, no sé si el linter dará error en eso.
Gracias!!

**Comment by nasivuela** [comment]
@younglust Aun veo la lógica del listado en el componente App, y el componente PokeList no es usado en ningún sitio. Dale una vuelta y me cuentas ;)

**Comment by younglust** [comment]
Hola @nasivuela creo que esta vez está, Gracias!!

**Comment by nasivuela** [comment]
Excelente!!!

Cierro y te dejo una última recomendación, pondría cada archivo de estilo junto a su componente ;)

![](https://media.giphy.com/media/24FRYDjnAbx411MSYf/giphy.gif)
